### ISSUE TITLE
Add initial Android SDK upgrade recipes

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-android#1]
## What problem are you trying to solve?
Provide a skeleton structure for recipes that migrate folks between various Android versions.

There's a few helpful first steps and useful resources we can pull from to provide a first couple steps, and then fill out more details in separate issues and pull requests.

## What precondition(s) should be checked before applying this recipe?
AGP used.
 
## Describe the situation before applying the recipe
```groovy
android {
    compileSdk 34
    ...
    defaultConfig {
        targetSdk 34
    }
}
```

## Describe the situation after applying the recipe
```groovy
android {
    compileSdk 35
    ...
    defaultConfig {
        targetSdk 35
    }
}
```

## Any additional context

The Android SDK docs provide a helpful reference of changes between Android versions; in particular the Removals are good to see:
- https://developer.android.com/sdk/api_diff/35/changes
- https://developer.android.com/sdk/api_diff/34/changes
- https://developer.android.com/sdk/api_diff/33/changes
- ...

There's also the next announced deprecations per version:
- https://developer.android.com/about/versions/15/deprecations
- https://developer.android.com/about/versions/12/deprecations
- ...

In addition to the API differences, there's also instructions to upgrading the SDK & AGP:
- https://developer.android.com/about/versions/15/setup-sdk
- https://developer.android.com/about/versions/14/setup-sdk
- https://developer.android.com/about/versions/13/setup-sdk
- ...

**Comment by adityabad** [comment]
Could I offer some help here?

**Comment by timtebeek** [comment]
> Hello @timtebeek Could I offer some help here?

Hi! Yes sure, welcome to contribute! I've added a rough skeleton; from there it's a matter of defining a first few steps to adopt newer SDK API versions. Perhaps there's a few good one-to-one replacements you know of that could be [implemented as a declarative recipe](https://docs.openrewrite.org/running-recipes/popular-recipe-guides/authoring-declarative-yaml-recipes)? Feel free to open a draft pull request with the changes you've identified, and then we'll take it from there.

**Comment by adityabad** [comment]
Thanks!! on it

**Comment by adityabad** [comment]
Hello @timtebeek .Here is a draft PR to understand if I am in the right direction. Please check and let me know

**Comment by timtebeek** [comment]
> Hello @timtebeek .Here is a draft PR to understand if I am in the right direction. Please check and let me know

Did you mean to include a link? I'm not seeing any draft PR or fork under your GitHub account.

**Comment by adityabad** [comment]
yes i was supposed to attach the link. https://github.com/elastic/elasticsearch/pull/112883

**Comment by timtebeek** [comment]
> yes i was supposed to attach the link. [elastic/elasticsearch#112883](https://github.com/elastic/elasticsearch/pull/112883) @timtebeek

I don't think that's quite right. Please join our OSS Slack to discuss your approach before going forward.

**Comment by timtebeek** [comment]
I've added a recipe to change the SDK version in build.gradle files already
- https://github.com/openrewrite/rewrite-android/pull/2

We can keep this issue open to gather further ideas for recipes that can hook into this framework of migration recipes.

**Comment by jjkester** [comment]
The Android SDK is quite a complex beast when it comes to versioning:

- The target version configured in the build requires a certain minimum Android Gradle Plugin (AGP) version ([source](https://developer.android.com/build/releases/gradle-plugin#api-level-support))
- Each AGP version is bound to a minimum (and likely a maximum) version of Gradle ([source](https://developer.android.com/build/releases/gradle-plugin#updating-gradle))

These are relatively simple to model (I am working on a PR for that).

Besides that:

- Changing the target SDK version usually means changing parts of the application due to differences in the platform behaviour or SDK APIs
- Changing the AGP version could mean that changes to the buildscript or dependencies are necessary

Android Studio has migrations and hits for that built-in, not sure if these are documented somewhere (exhaustively) and/or this code can be leveraged.

**Comment by timtebeek** [comment]
With https://github.com/openrewrite/rewrite-android/pull/3 merged I think we have enough of a basic structure covered that can be extended by folks looking to add specific migrations. Anyone is welcome to log additional issues or open up a draft pull request with desired migration steps.
